Use GPU for training
autonlab/DeepSurvivalMachines pull request #12
Opened 2020-11-24 21:27 UTC by Jeanselme

Check if GPU is available and train model on GPU (could be more elegant)

2020-11-27 16:06 UTC, chiragnagpal commented
We need to add to a GPU flag to the dsm_api.py module as well ...

2020-11-27 17:13 UTC, Jeanselme commented
Updated, should be more user friendly now

2020-12-11 16:06 UTC, chiragnagpal commented on dsm/dsm_api.py
> +               temp=1000., discount=1.0, cuda = torch.cuda.is_available()):
lets make cuda =False as default

2020-12-11 16:18 UTC, chiragnagpal requested changes

2020-12-11 16:18 UTC, chiragnagpal commented on dsm/dsm_api.py
> +    self.cuda = cuda
👍

2020-12-11 16:18 UTC, chiragnagpal commented on dsm/dsm_api.py
> +    if self.cuda:
👍

2020-12-11 16:18 UTC, chiragnagpal commented on dsm/dsm_api.py
> +  def cpu(self):
👍

2020-12-11 16:18 UTC, chiragnagpal commented on dsm/dsm_api.py
> +               distribution='Weibull', temp=1000., discount=1.0, typ='LSTM',
cuda=False

2020-12-11 16:18 UTC, chiragnagpal commented on dsm/utilities.py
> +  if model.cuda:
check if we really need this...

2021-01-27 16:13 UTC, chiragnagpal commented on dsm/dsm_api.py
> +    if self.cuda:
we should do it within each batch instead of the entire data

2021-01-27 16:13 UTC, chiragnagpal commented on dsm/dsm_api.py
> +    if self.cuda:
as with standard dsm -- maybe do this within each batch

2021-01-27 20:46 UTC, closed without merging