Evaluation updated to competing risks
autonlab/DeepSurvivalMachines pull request #29
Opened 2021-01-02 21:19 UTC by Jeanselme

2021-01-02 22:01 UTC, chiragnagpal reviewed
lets change the name of this function to _eval_nll

2021-01-02 22:01 UTC, chiragnagpal commented on dsm/dsm_api.py
> +  def _eval_conditional_loss(self, x, t, e):
_eval_conditional_loss if confusing ..lets call it _eval_nll

2021-01-03 23:38 UTC, chiragnagpal commented on dsm/dsm_api.py
> +                      "before calling `eval`.")
change eval to _eval_nll

2021-01-03 23:40 UTC, chiragnagpal commented on dsm/dsm_api.py
> +        Evaluates models with conditional loss
Add more descriptive docstring: specify what x, t , e requires and what the output is. The docstring should clearly describe that this function outputs the negative log likelihood of the dsm model

2021-01-03 23:40 UTC, chiragnagpal commented on dsm/dsm_api.py
> +        Evaluates models with conditional loss
Also specify how NLL is calculated in the presence of multiple competing risks

2021-01-03 23:41 UTC, chiragnagpal commented on dsm/dsm_api.py
> +from dsm.utilities import train_dsm, _get_padded_features, _get_padded_targets, \
break into 3 separate import statements 1) train_dsm, 2) _get_padded_features, _get_padded_targets and 3)    _reshape_tensor_with_nans

2021-01-03 23:43 UTC, chiragnagpal requested changes
@Jeanselme  would this work for both simple DSM and Recurrent DSM ? Please check, ideally it should. Also look at the inline comments I have added.

2021-01-04 07:54 UTC, Jeanselme commented
Yes, it does

2021-01-04 11:41 UTC, merged

2021-01-04 11:41 UTC, chiragnagpal commented
LGTM. Merged.